name: PixelSpawners
version: '1.0'
main: me.chalmano.pixelSpawners.PixelSpawners
api-version: '1.20'
authors: [ Chalmano, NOT_ACHI ]

dependencies:
  server:
    DecentHolograms:
      load: BEFORE
      required: true # This is the default when not present
