name: PixelSpawners
version: '1.0'
main: me.chalmano.pixelSpawners.PixelSpawners
api-version: '1.20'
authors: [ Lukka14 (Chalmano) ]

dependencies:
  server:
    DecentHolograms:
      load: BEFORE
      required: true
    Vault:
      load: BEFORE
      required: true

commands:
  pixelspawners:
    description: "Reload plugin configurations"
    usage: "/ps reload"
    aliases: [ps]
    permission: pixelspawners.reload
    permission-message: "You do not have permission to use this command"